### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by AoBaLuoZi** [ddcw/ibd2sql#39]
File "C:\Users\11738\Desktop\ibd2sql\main.py", line 160, in <module>
    ddcw.get_sql()
    ~~~~~~~~~~~~^^
  File "C:\Users\11738\Desktop\ibd2sql\ibd2sql\ibd2sql.py", line 200, in get_sql
    aa = index(self.read(),table=self.table, idx=self.table.cluster_index_id, debug=self.debug,f=self.f)
  File "C:\Users\11738\Desktop\ibd2sql\ibd2sql\innodb_page_index.py", line 654, in __init__
    super().__init__(*args,**kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\11738\Desktop\ibd2sql\ibd2sql\innodb_page_index.py", line 83, in __init__
    super().__init__(*args,**kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\11738\Desktop\ibd2sql\ibd2sql\innodb_page.py", line 176, in __init__
    self.FIL_PAGE_SPACE_OR_CHKSUM, self.FIL_PAGE_OFFSET, self.FIL_PAGE_PREV, self.FIL_PAGE_NEXT, self.FIL_PAGE_LSN, self.FIL_PAGE_TYPE, self.FIL_PAGE_FILE_FLUSH_LSN = struct.unpack('>4LQHQ',bdata[:34])

                                               ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 34 bytes

**Comment by AoBaLuoZi** [comment]
执行报错

**Comment by ddcw** [comment]
这个报错是读取ibd文件的时候 没有拿到34字节, 即**ibd文件是空的**. 可以查看下数据文件的大小是否为0呢

**Comment by AoBaLuoZi** [comment]
&nbsp;C:\Users\11738\Desktop\formalexam\exam_answer.ibd --ddl --sql &gt; C:\Users\11738\Desktop\exam\exam_answer.sql 导出来文件中文乱码&nbsp;
这个报错是数据转换了一半 然后报的错&nbsp;


&nbsp;


哈哈哈哈
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月25日(星期三) 中午1:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ddcw/ibd2sql] 报错 (Issue #39)















这个报错是读取ibd文件的时候 没有拿到34字节, 即ibd文件是空的. 可以查看下数据文件的大小是否为0呢

**Comment by ddcw** [comment]
这啥报错....  
转换到一半的时候报错, 大概率是坏块. (确认是否存在坏块: https://github.com/ddcw/ddcw/tree/master/python/check_innodb_file)
处理方法: 可以强制解析每一页. 即文档最后一个例子: https://github.com/ddcw/ibd2sql/blob/main/docs/USAGE.md

> 解析的时候, 偷懒没有对数据做检查....

**Comment by AoBaLuoZi** [comment]
C:\Users\11738\Desktop\ddcw\python\check_innodb_file&gt;python check_innodb_file.py C:\Users\11738\Desktop\formalexam\exam_answer.ibd
BAD PAGE: 2937
BAD PAGE: 2938
BAD PAGE: 2939 这是损坏了吗



&nbsp;


哈哈哈哈
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月25日(星期三) 中午1:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ddcw/ibd2sql] 报错 (Issue #39)















这啥报错....
转换到一半的时候报错, 大概率是坏块. (确认是否存在坏块: https://github.com/ddcw/ddcw/tree/master/python/check_innodb_file)
处理方法: 可以强制解析每一页. 即文档最后一个例子: https://github.com/ddcw/ibd2sql/blob/main/docs/USAGE.md

解析的时候, 偷懒没有对数据做检查....

**Comment by ddcw** [comment]
是的, 列出的那几页就算坏块的.....
可以强制解析每1页(坏块的页也会尽量解析...). 就是速度慢一点: https://github.com/ddcw/ibd2sql/blob/main/docs/USAGE.md

**Comment by AoBaLuoZi** [comment]
重定向出来的.sql 中文乱码&nbsp;&nbsp;这个咋办


&nbsp;


哈哈哈哈
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月25日(星期三) 下午2:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ddcw/ibd2sql] 报错 (Issue #39)















是的, 列出的那几页就算坏块的.....
可以强制解析每1页(坏块的页也会尽量解析...). 就是速度慢一点: https://github.com/ddcw/ibd2sql/blob/main/docs/USAGE.md

**Comment by AoBaLuoZi** [comment]
C:\Users\11738\Desktop\ibd2sql&gt;python main.py C:\Users\11738\Desktop\formalexam\exam_answer.ibd --sdi-table C:\Users\11738\Desktop\formalexam\exam_answer.ibd --sql &gt; C:\Users\11738\Desktop\exam\exam_answer.sql
Traceback (most recent call last):
&nbsp; File "C:\Users\11738\Desktop\ibd2sql\main.py", line 165, in <module&gt;
&nbsp; &nbsp; ddcw.get_sql()
&nbsp; &nbsp; ~~~~~~~~~~~~^^
&nbsp; File "C:\Users\11738\Desktop\ibd2sql\ibd2sql\ibd2sql.py", line 200, in get_sql
&nbsp; &nbsp; aa = index(self.read(),table=self.table, idx=self.table.cluster_index_id, debug=self.debug,f=self.f)
&nbsp; File "C:\Users\11738\Desktop\ibd2sql\ibd2sql\innodb_page_index.py", line 654, in __init__
&nbsp; &nbsp; super().__init__(*args,**kwargs)
&nbsp; &nbsp; ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
&nbsp; File "C:\Users\11738\Desktop\ibd2sql\ibd2sql\innodb_page_index.py", line 83, in __init__
&nbsp; &nbsp; super().__init__(*args,**kwargs)
&nbsp; &nbsp; ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
&nbsp; File "C:\Users\11738\Desktop\ibd2sql\ibd2sql\innodb_page.py", line 176, in __init__
&nbsp; &nbsp; self.FIL_PAGE_SPACE_OR_CHKSUM, self.FIL_PAGE_OFFSET, self.FIL_PAGE_PREV, self.FIL_PAGE_NEXT, self.FIL_PAGE_LSN, self.FIL_PAGE_TYPE, self.FIL_PAGE_FILE_FLUSH_LSN = struct.unpack('&gt;4LQHQ',bdata[:34])


&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 34 bytes&nbsp;&nbsp;

加了 --sdi-table 还是报错


&nbsp;


哈哈哈哈
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月25日(星期三) 下午2:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ddcw/ibd2sql] 报错 (Issue #39)















是的, 列出的那几页就算坏块的.....
可以强制解析每1页(坏块的页也会尽量解析...). 就是速度慢一点: https://github.com/ddcw/ibd2sql/blob/main/docs/USAGE.md

**Comment by ddcw** [comment]
--sdi-table是处理分区表和5.x场景的, 你这个属于坏块, 参考如下方法:  win环境的, 之前也提供过, 你翻下issue呢
```shell
filename="/tmp/ddcw_alltype_table.ibd" # 要解析的ibd文件名
python3 main.py ${filename} --ddl # 获取表结构信息
filesize=`stat -c %s ${filename}`
maxpagecount=$[ ${filesize} / 16384 ]
current_page=1
while [ ${current_page} -le ${maxpagecount} ];do
	echo "-- ${filename} PAGE NO: ${current_page}"; 
	current_page=$[ ${current_page} + 1 ]
	python3 main.py ${filename} --sql --page-start ${current_page} --page-count 1 2>/dev/null ; 
done
```

**Comment by AoBaLuoZi** [comment]
好 非常感谢


&nbsp;


哈哈哈哈
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月25日(星期三) 下午2:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ddcw/ibd2sql] 报错 (Issue #39)















--sdi-table是处理分区表和5.x场景的, 你这个属于坏块, 参考如下方法:  win环境的, 之前也提供过, 你翻下issue呢
filename="/tmp/ddcw_alltype_table.ibd" # 要解析的ibd文件名python3 main.py ${filename} --ddl # 获取表结构信息filesize=`stat -c %s ${filename}`maxpagecount=$[ ${filesize} / 16384 ]current_page=1while [ ${current_page} -le ${maxpagecount} ];doecho "-- ${filename} PAGE NO: ${current_page}"; current_page=$[ ${current_page} + 1 ]python3 main.py ${filename} --sql --page-start ${current_page} --page-count 1 2&gt;/dev/null ; done
