### ISSUE TITLE
报错了，大大

### ISSUE THREAD

**Issue by lmxtsy** [ddcw/ibd2sql#41]
D:\ibd2sql-main>python main.py sj4.ibd --sdi-table sj8.ibd --mysql5 --ddl
Traceback (most recent call last):
  File "D:\ibd2sql-main\main.py", line 144, in <module>
    ddcw.init()
  File "D:\ibd2sql-main\ibd2sql\ibd2sql.py", line 146, in init
    self.inode = inode(self.read(),MYSQL5=self.MYSQL5)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: __init__() should return None, not 'bool'

sj4是5.几的文件

**Comment by ddcw** [comment]
这个报错说明  sj4.ibd 文件中第2页inode有问题(比如:坏块, 也可能是不在这.).  mysql的版本是多少呢? 万能的方法就是 [文档](https://github.com/ddcw/ibd2sql/blob/main/docs/USAGE.md)里的**ibd文件损坏的场景**
第0页: fsp (ibd的基础信息和xds,keyring等)
第1页: insert buffer
第2页: inode buffer (索引信息)
第3页: sdi (8.0才有)
