### ISSUE TITLE
KeyError: 32 [27124] Failed to execute script 'main' due to unhandled exception!   测试报错

### ISSUE THREAD

**Issue by theone1900** [ddcw/ibd2sql#9]
[新建文本文档 (4).txt](https://github.com/ddcw/ibd2sql/files/14692564/4.txt)

[2024-03-21 16:59:54] [DEBUG] ######################################## FIELD INFO END ######################################
[2024-03-21 16:59:54] [DEBUG] 没得索引
[2024-03-21 16:59:54] [DEBUG] ROW INIT FINISH FOR < `test`.`aaa` >

[2024-03-21 16:59:54] [DEBUG] SET FILTER (0, 281474976710656) (0, 72057594037927936)
[2024-03-21 16:59:54] [DEBUG] ################## READ ROW START (PAGE NO:5) ########################
[2024-03-21 16:59:54] [DEBUG] READ ALL ROWS FROM PAGE (PAGE_ID=5)
[2024-03-21 16:59:54] [DEBUG] RESET offset TO PAGE_NEW_INFIMUM (99)
[2024-03-21 16:59:54] [DEBUG] NO:1 READ RECORD HEADER (5 bytes) _offset:99 offset:99 START
[2024-03-21 16:59:54] [DEBUG]   THIS ROW IS PAGE_NEW_INFIMUM, WILL CONTINUE. (offset:99)
[2024-03-21 16:59:54] [DEBUG] NO:2 READ RECORD HEADER (5 bytes) _offset:132 offset:132 START
[2024-03-21 16:59:54] [DEBUG]   READ RECORD HEADER (5 bytes) _offset:127 offset:132 FINISH
[2024-03-21 16:59:54] [DEBUG]   PAGE NO     : 5
[2024-03-21 16:59:54] [DEBUG]   READ ROW NO : 0   CURRENT_OFFSET:132
[2024-03-21 16:59:54] [DEBUG]   REC INSTANT : False
[2024-03-21 16:59:54] [DEBUG]   REC DELETED : False
[2024-03-21 16:59:54] [DEBUG]   REC MIN_REC : False
[2024-03-21 16:59:54] [DEBUG]   REC OWNED   : 0
[2024-03-21 16:59:54] [DEBUG]   REC HEAP_NO : 16
[2024-03-21 16:59:54] [DEBUG]   REC TYPE    : 0
[2024-03-21 16:59:54] [DEBUG]   REC NEXT    : 436
[2024-03-21 16:59:54] [DEBUG]   20 bytes ON BOTH SIDES OF RECORD, b'\x04\x00\x0b\x00\x00supremum\x00@\x00\x00\x00 |', b'\x00\x00\x10\x01\xb4\x00\x00\x00\x00\x03\x10\x00\x00\x00\x00\t"\x81\x00\x00'
[2024-03-21 16:59:54] [DEBUG] GET COUNT COLUMN FOR THIS ROW
[2024-03-21 16:59:54] [DEBUG]   READ COLUM COUNT
[2024-03-21 16:59:54] [DEBUG]   READ COLUM COUNT FINISH
[2024-03-21 16:59:54] [DEBUG]   THIS ROW HAS 51 FILEDS
[2024-03-21 16:59:54] [DEBUG] READ NULL BITMASK
[2024-03-21 16:59:54] [DEBUG]   NULLABLE FILED COUNT: 7  NULLABLE FIELD COUNT(FOR INSTANT):0
[2024-03-21 16:59:54] [DEBUG]   NULL BITMASK: COUNT:7  ID: 124 [0, 1, 1, 1, 1, 1, 0, 0]
[2024-03-21 16:59:54] [DEBUG] READ KEY FILED
[2024-03-21 16:59:54] [DEBUG]   NO CLUSTER KEY.WILL READ 6 bytes(ROWID)
[2024-03-21 16:59:54] [DEBUG]    ROW_ID:784
[2024-03-21 16:59:54] [DEBUG] READ TRX(6) AND ROLLPTR(7) INFO
[2024-03-21 16:59:54] [DEBUG]   TRX: 2338  ROLLPTR: 36310272013373301
[2024-03-21 16:59:54] [DEBUG] READ THE REST OF FIELD. (column count: 49)
[2024-03-21 16:59:54] [DEBUG]   READ FIELD COLNO: 1 NAME: Host TYPE: char(255) CT: char
[2024-03-21 16:59:54] [DEBUG]   COL 1 Host REQUIRE NOT NULL. READ DATA
[2024-03-21 16:59:54] [DEBUG]   VAR FILED VAR SIZE: 32
[2024-03-21 16:59:54] [DEBUG]   151 ----> 183 data:%  bdata:b'%                               '
[2024-03-21 16:59:54] [DEBUG]   READ FIELD COLNO: 2 NAME: User TYPE: char(32) CT: char
[2024-03-21 16:59:54] [DEBUG]   COL 2 User REQUIRE NOT NULL. READ DATA
[2024-03-21 16:59:54] [DEBUG]   VAR FILED VAR SIZE: 0
[2024-03-21 16:59:54] [DEBUG]   183 ----> 183 data:  bdata:b''
[2024-03-21 16:59:54] [DEBUG]   READ FIELD COLNO: 3 NAME: Select_priv TYPE: enum('N','Y') CT: enum
[2024-03-21 16:59:54] [DEBUG]   COL 3 Select_priv REQUIRE NOT NULL. READ DATA
Traceback (most recent call last):
  File "main.py", line 177, in <module>
  File "ibd2sql\ibd2sql.py", line 229, in get_sql
  File "ibd2sql\innodb_page_index.py", line 224, in read_row
  File "ibd2sql\innodb_page_index.py", line 394, in _read_all_row
  File "ibd2sql\innodb_page_index.py", line 186, in _read_field
KeyError: 32
[27124] Failed to execute script 'main' due to unhandled exception!

C:\Users\ZMI\Desktop\data\test>

**Comment by ddcw** [comment]
> [新建文本文档 (4).txt](https://github.com/ddcw/ibd2sql/files/14692564/4.txt)
> 
> [2024-03-21 16:59:54] [DEBUG] ######################################## FIELD INFO END ###################################### [2024-03-21 16:59:54] [DEBUG] 没得索引 [2024-03-21 16:59:54] [DEBUG] ROW INIT FINISH FOR < `test`.`aaa` >
> 
> [2024-03-21 16:59:54] [DEBUG] SET FILTER (0, 281474976710656) (0, 72057594037927936) [2024-03-21 16:59:54] [DEBUG] ################## READ ROW START (PAGE NO:5) ######################## [2024-03-21 16:59:54] [DEBUG] READ ALL ROWS FROM PAGE (PAGE_ID=5) [2024-03-21 16:59:54] [DEBUG] RESET offset TO PAGE_NEW_INFIMUM (99) [2024-03-21 16:59:54] [DEBUG] NO:1 READ RECORD HEADER (5 bytes) _offset:99 offset:99 START [2024-03-21 16:59:54] [DEBUG] THIS ROW IS PAGE_NEW_INFIMUM, WILL CONTINUE. (offset:99) [2024-03-21 16:59:54] [DEBUG] NO:2 READ RECORD HEADER (5 bytes) _offset:132 offset:132 START [2024-03-21 16:59:54] [DEBUG] READ RECORD HEADER (5 bytes) _offset:127 offset:132 FINISH [2024-03-21 16:59:54] [DEBUG] PAGE NO : 5 [2024-03-21 16:59:54] [DEBUG] READ ROW NO : 0 CURRENT_OFFSET:132 [2024-03-21 16:59:54] [DEBUG] REC INSTANT : False [2024-03-21 16:59:54] [DEBUG] REC DELETED : False [2024-03-21 16:59:54] [DEBUG] REC MIN_REC : False [2024-03-21 16:59:54] [DEBUG] REC OWNED : 0 [2024-03-21 16:59:54] [DEBUG] REC HEAP_NO : 16 [2024-03-21 16:59:54] [DEBUG] REC TYPE : 0 [2024-03-21 16:59:54] [DEBUG] REC NEXT : 436 [2024-03-21 16:59:54] [DEBUG] 20 bytes ON BOTH SIDES OF RECORD, b'\x04\x00\x0b\x00\x00supremum\x00@\x00\x00\x00 |', b'\x00\x00\x10\x01\xb4\x00\x00\x00\x00\x03\x10\x00\x00\x00\x00\t"\x81\x00\x00' [2024-03-21 16:59:54] [DEBUG] GET COUNT COLUMN FOR THIS ROW [2024-03-21 16:59:54] [DEBUG] READ COLUM COUNT [2024-03-21 16:59:54] [DEBUG] READ COLUM COUNT FINISH [2024-03-21 16:59:54] [DEBUG] THIS ROW HAS 51 FILEDS [2024-03-21 16:59:54] [DEBUG] READ NULL BITMASK [2024-03-21 16:59:54] [DEBUG] NULLABLE FILED COUNT: 7 NULLABLE FIELD COUNT(FOR INSTANT):0 [2024-03-21 16:59:54] [DEBUG] NULL BITMASK: COUNT:7 ID: 124 [0, 1, 1, 1, 1, 1, 0, 0] [2024-03-21 16:59:54] [DEBUG] READ KEY FILED [2024-03-21 16:59:54] [DEBUG] NO CLUSTER KEY.WILL READ 6 bytes(ROWID) [2024-03-21 16:59:54] [DEBUG] ROW_ID:784 [2024-03-21 16:59:54] [DEBUG] READ TRX(6) AND ROLLPTR(7) INFO [2024-03-21 16:59:54] [DEBUG] TRX: 2338 ROLLPTR: 36310272013373301 [2024-03-21 16:59:54] [DEBUG] READ THE REST OF FIELD. (column count: 49) [2024-03-21 16:59:54] [DEBUG] READ FIELD COLNO: 1 NAME: Host TYPE: char(255) CT: char [2024-03-21 16:59:54] [DEBUG] COL 1 Host REQUIRE NOT NULL. READ DATA [2024-03-21 16:59:54] [DEBUG] VAR FILED VAR SIZE: 32 [2024-03-21 16:59:54] [DEBUG] 151 ----> 183 data:% bdata:b'% ' [2024-03-21 16:59:54] [DEBUG] READ FIELD COLNO: 2 NAME: User TYPE: char(32) CT: char [2024-03-21 16:59:54] [DEBUG] COL 2 User REQUIRE NOT NULL. READ DATA [2024-03-21 16:59:54] [DEBUG] VAR FILED VAR SIZE: 0 [2024-03-21 16:59:54] [DEBUG] 183 ----> 183 data: bdata:b'' [2024-03-21 16:59:54] [DEBUG] READ FIELD COLNO: 3 NAME: Select_priv TYPE: enum('N','Y') CT: enum [2024-03-21 16:59:54] [DEBUG] COL 3 Select_priv REQUIRE NOT NULL. READ DATA Traceback (most recent call last): File "main.py", line 177, in File "ibd2sql\ibd2sql.py", line 229, in get_sql File "ibd2sql\innodb_page_index.py", line 224, in read_row File "ibd2sql\innodb_page_index.py", line 394, in _read_all_row File "ibd2sql\innodb_page_index.py", line 186, in _read_field KeyError: 32 [27124] Failed to execute script 'main' due to unhandled exception!
> 
> C:\Users\ZMI\Desktop\data\test>

看起来是空字段处理和char(255)的问题, 我会尽快修复的. 如果你现在要测试的话, 可以试着删除 第一个字段`alter table test.aaa drop column Host;`

**Comment by ddcw** [comment]
根本原因是:  host字段的字符集是ascii , 但我全部都当作utf8来处理的, 导致识别的size出现了偏差. 从而导致后面解析有问题.
短期内不会修复这个BUG. (几乎没见过一张表里面使用多种字符集的, (除了这个mysql.user表.))

**Comment by ddcw** [comment]
> [新建文本文档 (4).txt](https://github.com/ddcw/ibd2sql/files/14692564/4.txt)
> 
> [2024-03-21 16:59:54] [DEBUG] ######################################## FIELD INFO END ###################################### [2024-03-21 16:59:54] [DEBUG] 没得索引 [2024-03-21 16:59:54] [DEBUG] ROW INIT FINISH FOR < `test`.`aaa` >
> 
> [2024-03-21 16:59:54] [DEBUG] SET FILTER (0, 281474976710656) (0, 72057594037927936) [2024-03-21 16:59:54] [DEBUG] ################## READ ROW START (PAGE NO:5) ######################## [2024-03-21 16:59:54] [DEBUG] READ ALL ROWS FROM PAGE (PAGE_ID=5) [2024-03-21 16:59:54] [DEBUG] RESET offset TO PAGE_NEW_INFIMUM (99) [2024-03-21 16:59:54] [DEBUG] NO:1 READ RECORD HEADER (5 bytes) _offset:99 offset:99 START [2024-03-21 16:59:54] [DEBUG] THIS ROW IS PAGE_NEW_INFIMUM, WILL CONTINUE. (offset:99) [2024-03-21 16:59:54] [DEBUG] NO:2 READ RECORD HEADER (5 bytes) _offset:132 offset:132 START [2024-03-21 16:59:54] [DEBUG] READ RECORD HEADER (5 bytes) _offset:127 offset:132 FINISH [2024-03-21 16:59:54] [DEBUG] PAGE NO : 5 [2024-03-21 16:59:54] [DEBUG] READ ROW NO : 0 CURRENT_OFFSET:132 [2024-03-21 16:59:54] [DEBUG] REC INSTANT : False [2024-03-21 16:59:54] [DEBUG] REC DELETED : False [2024-03-21 16:59:54] [DEBUG] REC MIN_REC : False [2024-03-21 16:59:54] [DEBUG] REC OWNED : 0 [2024-03-21 16:59:54] [DEBUG] REC HEAP_NO : 16 [2024-03-21 16:59:54] [DEBUG] REC TYPE : 0 [2024-03-21 16:59:54] [DEBUG] REC NEXT : 436 [2024-03-21 16:59:54] [DEBUG] 20 bytes ON BOTH SIDES OF RECORD, b'\x04\x00\x0b\x00\x00supremum\x00@\x00\x00\x00 |', b'\x00\x00\x10\x01\xb4\x00\x00\x00\x00\x03\x10\x00\x00\x00\x00\t"\x81\x00\x00' [2024-03-21 16:59:54] [DEBUG] GET COUNT COLUMN FOR THIS ROW [2024-03-21 16:59:54] [DEBUG] READ COLUM COUNT [2024-03-21 16:59:54] [DEBUG] READ COLUM COUNT FINISH [2024-03-21 16:59:54] [DEBUG] THIS ROW HAS 51 FILEDS [2024-03-21 16:59:54] [DEBUG] READ NULL BITMASK [2024-03-21 16:59:54] [DEBUG] NULLABLE FILED COUNT: 7 NULLABLE FIELD COUNT(FOR INSTANT):0 [2024-03-21 16:59:54] [DEBUG] NULL BITMASK: COUNT:7 ID: 124 [0, 1, 1, 1, 1, 1, 0, 0] [2024-03-21 16:59:54] [DEBUG] READ KEY FILED [2024-03-21 16:59:54] [DEBUG] NO CLUSTER KEY.WILL READ 6 bytes(ROWID) [2024-03-21 16:59:54] [DEBUG] ROW_ID:784 [2024-03-21 16:59:54] [DEBUG] READ TRX(6) AND ROLLPTR(7) INFO [2024-03-21 16:59:54] [DEBUG] TRX: 2338 ROLLPTR: 36310272013373301 [2024-03-21 16:59:54] [DEBUG] READ THE REST OF FIELD. (column count: 49) [2024-03-21 16:59:54] [DEBUG] READ FIELD COLNO: 1 NAME: Host TYPE: char(255) CT: char [2024-03-21 16:59:54] [DEBUG] COL 1 Host REQUIRE NOT NULL. READ DATA [2024-03-21 16:59:54] [DEBUG] VAR FILED VAR SIZE: 32 [2024-03-21 16:59:54] [DEBUG] 151 ----> 183 data:% bdata:b'% ' [2024-03-21 16:59:54] [DEBUG] READ FIELD COLNO: 2 NAME: User TYPE: char(32) CT: char [2024-03-21 16:59:54] [DEBUG] COL 2 User REQUIRE NOT NULL. READ DATA [2024-03-21 16:59:54] [DEBUG] VAR FILED VAR SIZE: 0 [2024-03-21 16:59:54] [DEBUG] 183 ----> 183 data: bdata:b'' [2024-03-21 16:59:54] [DEBUG] READ FIELD COLNO: 3 NAME: Select_priv TYPE: enum('N','Y') CT: enum [2024-03-21 16:59:54] [DEBUG] COL 3 Select_priv REQUIRE NOT NULL. READ DATA Traceback (most recent call last): File "main.py", line 177, in File "ibd2sql\ibd2sql.py", line 229, in get_sql File "ibd2sql\innodb_page_index.py", line 224, in read_row File "ibd2sql\innodb_page_index.py", line 394, in _read_all_row File "ibd2sql\innodb_page_index.py", line 186, in _read_field KeyError: 32 [27124] Failed to execute script 'main' due to unhandled exception!
> 
> C:\Users\ZMI\Desktop\data\test>

已修复, 你下载[最新版](https://github.com/ddcw/ibd2sql/archive/refs/heads/main.zip)试下呢
